# Generated by Django 5.2.8 on 2025-11-22 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('ambito', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='TipoDano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'tipo_daño',
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_trabajo',
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_alquiler', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dias_alquiler', models.IntegerField()),
                ('dni_cliente', models.ForeignKey(db_column='dni_cliente', on_delete=django.db.models.deletion.PROTECT, to='gestion.cliente')),
                ('dni_empleado', models.ForeignKey(db_column='dni_empleado', on_delete=django.db.models.deletion.PROTECT, to='gestion.empleado')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='gestion.estado')),
            ],
            options={
                'db_table': 'alquiler',
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('esta_pagada', models.BooleanField(default=False)),
                ('id_alquiler', models.ForeignKey(db_column='id_alquiler', on_delete=django.db.models.deletion.CASCADE, to='gestion.alquiler')),
            ],
            options={
                'db_table': 'multa',
            },
        ),
        migrations.CreateModel(
            name='Dano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alquiler', models.ForeignKey(db_column='id_alquiler', on_delete=django.db.models.deletion.CASCADE, to='gestion.alquiler')),
                ('tipo_dano', models.ForeignKey(db_column='tipo_dano', on_delete=django.db.models.deletion.PROTECT, to='gestion.tipodano')),
            ],
            options={
                'db_table': 'daño',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('patente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=30)),
                ('precio_x_dia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, to='gestion.estado')),
                ('nombre_marca', models.ForeignKey(db_column='nombre_marca', on_delete=django.db.models.deletion.PROTECT, to='gestion.marca')),
            ],
            options={
                'db_table': 'vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('id_tipo_trabajo', models.ForeignKey(db_column='id_tipo_trabajo', on_delete=django.db.models.deletion.PROTECT, to='gestion.tipotrabajo')),
                ('patente', models.ForeignKey(db_column='patente', on_delete=django.db.models.deletion.CASCADE, to='gestion.vehiculo')),
            ],
            options={
                'db_table': 'mantenimiento',
            },
        ),
        migrations.AddField(
            model_name='alquiler',
            name='patente_vehiculo',
            field=models.ForeignKey(db_column='patente_vehiculo', on_delete=django.db.models.deletion.PROTECT, to='gestion.vehiculo'),
        ),
    ]
