from .marca import Marca
from .estado import Estado
from .tipo_trabajo import TipoTrabajo
from .tipo_dano import TipoDano
from .cliente import Cliente
from .empleado import Empleado
from .vehiculo import Vehiculo
from .alquiler import Alquiler
from .mantenimiento import Mantenimiento
from .multa import Multa
from .dano import Dano